[package]
name = "open_aoe_types"
description = """
    OpenAOE types crate
"""
license = "MIT"
version = "0.1.0"
keywords = ["aoe", "age", "empires", "genie", "engine"]
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]

[dependencies]
sdl2 = "0.21"
